GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Me, a former physicist, just launched my first project using Elixir and Phoenix.",
    "author": "Felipe Lincoln",
    "url": "https://dev.to/felipelincoln/me-a-former-physicist-just-launched-my-first-project-using-elixir-and-phoenix-8k",
    "likes": 2
}
