GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "New Blog - Full Stack Open 2022 Part 4",
    "author": "Jonathan Caburnay",
    "url": "https://fullstackopen.com/en/part4/testing_the_backend#exercises-4-8-4-12"
}
###
PUT http://localhost:3001/api/blogs/6282508d7ee58abc1211aadf
Content-Type: application/json

{
    "likes": 2022
}

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "binong",
    "name": "Jonathan Caburnay",
    "password": "password123"
}