GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "New Blog - Full Stack Open 2022 Part 4",
    "author": "Jonathan Caburnay",
    "url": "https://fullstackopen.com/en/part4/testing_the_backend#exercises-4-8-4-12"
}
###
PUT http://localhost:3001/api/blogs/6282508d7ee58abc1211aadf
Content-Type: application/json

{
    "likes": 2022
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "bin",
    "name": "Jonathan Caburnay",
    "password": "123"
}
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "New Blog - Full Stack Open 2022 Part 4",
    "author": "Jonathan Caburnay",
    "url": "https://fullstackopen.com/en/part4/testing_the_backend#exercises-4-8-4-12",
    "userId": "628b98f16fbdf0548d723707"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "bin",
    "password": "123"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpbiIsImlkIjoiNjI4Yjk4ZjE2ZmJkZjA1NDhkNzIzNzA3IiwiaWF0IjoxNjUzMzIxNDQzfQ.VSmHBSo2sBc3WQRdbAUNk0CAKNFtne1TGK91pqoagWU

{
    "title": "Refactored getTokenFrom",
    "author": "Jonathan Caburnay",
    "url": "https://fullstackopen.com/en/part4/token_authentication#exercises-4-15-4-23"
}